[project]
name = "semaflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.23.0",
    "pyyaml>=6.0",
    "duckdb>=0.10.2",
]

[dependency-groups]
dev = [
    "maturin>=1.10.2",
]

[build-system]
requires = ["maturin>=1.10.2"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "semaflowrs/Cargo.toml"
features = ["python"]
python-source = "semaflow"
